import type { Metadata } from "next";
import { Epilogue, Inter } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const epilogueSans = Epilogue({
  variable: "--font-epilogue",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const openSauceSans = localFont({
  src: "../fonts/OpenSauceSans-Medium.ttf",
  display: "swap",
  variable: "--font-openSauceSans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${epilogueSans.variable} ${openSauceSans.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
